/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b04a6c24-e237-4431-9129-8de296348159",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IM4b0MMrj",
    "aws_user_pools_web_client_id": "6rr9lalbm8bu8gt4khla38jauv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6zgot5uoh5cubo7scj55x7g6oy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-j7kiqmh4kffidgl3qsr6cjj2fu"
};


export default awsmobile;
