/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0a650260-d1de-4249-b612-aa0b406f5754",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_527EfCcqe",
    "aws_user_pools_web_client_id": "1rj5rcsgqd2rh0ntuq5lcpnqet",
    "oauth": {}
};


export default awsmobile;
